CREATE INDEX "HR"."PARTITION1_IDX_INT" ON "HR"."PARTITION1_INT"
  (
    "CUSTOMER_ID"
  )
  PCTFREE 10 INITRANS 2 MAXTRANS 255 STORAGE
  (
    BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT
  )
  LOCAL
/


ALTER INDEX "HR"."PARTITION1_IDX" NOPARALLEL;

